### ISSUE TITLE
Volumes not being spread across wells correctly (Vish/Merck issue)

### ISSUE THREAD

**Issue by jarpinosynthace** [antha-lang/antha#354] opened 2017-04-25 16:09 UTC
Element: Aliquot

Purpose: Aliquoting 1mL volumes in to 96DSW from a 12 column trough.

Problem: When defining a 50mL SolutionVolume, 50 NumberofAliquots and 1mL VolumePerAliquot Antha assumes that it can fill an a single column with 50mLs of solution. This is not possible as the capacity for a strip will be ~14-15mL volume.

The Aliquot element functions fine when using low volume permutations.

Please find the bundle attached
[1x Aliquot_24042017_VS (1).txt](https://github.com/antha-lang/antha/files/955687/1x.Aliquot_24042017_VS.1.txt)

**Comment by jarpinosynthace** [comment] 2017-04-25 16:10
Hi Sid, Vish asked me to submit this issue, let me know if you need anymore details on it.

**Comment by vishalsanchania** [comment] 2017-04-27 14:06
Hey Sid, found another example of the same/similar error. 

I'm using the "Transfer_multi" element. 

Antha appears to be insensitive to the fact that 20mL cannot be placed into a single 96-well plate well, and that this 20mL cannot be transferred into a single 384 plate-well well without overfilling. 

![screen shot 2017-04-27 at 15 00 45](https://cloud.githubusercontent.com/assets/23479880/25486988/cc237018-2b5a-11e7-9204-3e4bfdddada1.png)
![screen shot 2017-04-27 at 15 01 25](https://cloud.githubusercontent.com/assets/23479880/25486989/cc2a1c56-2b5a-11e7-88cc-4d198cb65be4.png)

[1x Transfer_multi.txt](https://github.com/antha-lang/antha/files/961816/1x.Transfer_multi.txt)

**Comment by m-i-sadowski** [comment] 2017-04-28 14:58
On further discussion with Chris I think the desired behaviour is actually not strictly a bug - it's more like a very highly desirable feature. Currently the system is not designed to enforce volume limits in this way.

I'll look into this asap and determine how to improve matters

**Comment by vishalsanchania** [comment] 2017-05-08 13:59
Hi Sid,

Updating this bug with Jaja's recent findings.

When using the "Aliquot" element and pipetting a 1mL volume from a 100mL starting volume from a 12 column trough, Antha adds 100mL directly into A1 of the trough. This would not be physically possbile. 

On altering the VolumeperAliquot variable from 1mL to 1000uL the problem is resolved. Hopefully this will aid any troubleshooting efforts. 

NB: there is a big problem of inefficient tip use here too.

Figure below shows trough with 100mL in A1 when value set at 1mL:


![screen shot 2017-05-08 at 14 51 21](https://cloud.githubusercontent.com/assets/23479880/25807251/0d1b1a5c-33fe-11e7-8ce5-24954ef72c8c.png)

[1x Aliquot (2).txt](https://github.com/antha-lang/antha/files/983658/1x.Aliquot.2.txt)


Figure below shows trough with 100mL volume distributed across all well A1- A12 when value set to 1000uL: 
![screen shot 2017-05-08 at 14 50 49](https://cloud.githubusercontent.com/assets/23479880/25807271/2565574e-33fe-11e7-9c72-b330f3dd2670.png)

[1x Aliquot (1).txt](https://github.com/antha-lang/antha/files/983656/1x.Aliquot.1.txt)


Thank you!

**Comment by jarpinosynthace** [comment] 2017-05-09 09:39
Hi Sid, Sorry, just to add to this, similar volume errors with too much being put into wells using the Aliquot element. Attached bundle file:
[1x Aliquot.json.zip](https://github.com/antha-lang/antha/files/986179/1x.Aliquot.json.zip)
![screen shot 2017-05-09 at 10 34 14](https://cloud.githubusercontent.com/assets/22589193/25844861/c1c27090-34a3-11e7-8ea8-0b1eac054b38.png)

**Comment by jarpinosynthace** [comment] 2017-05-09 10:09
sorry another weird behaviour. If you have two copies of aliquot, there is a parameter to optimiseplateuseage such that the two sets of aliquots get put into the same destination plate. However, the aliquots are put into the destination plate in a random order rather than keeping the two sets of aliquots together (I hope this makes sense, best to see this after simulating and looking at plate prep. Again the volume issue on the source plate (and a weird layout of the two solutions maybe?)
[2x Aliquot (1).json.zip](https://github.com/antha-lang/antha/files/986274/2x.Aliquot.1.json.zip)

**Comment by m-i-sadowski** [comment] 2017-05-10 08:46
closed by antha-lang/antha fec3105088160c36fa90c0ce932e275425caf9da

**Closed by m-i-sadowski** 2017-05-10 08:46 UTC
Labels: bug
